#!/bin/sh
# Written by AI, from this chat: https://claude.ai/share/e93e1767-dc2a-484a-8f0f-29c3b7d0ae48

case "$1" in
    start)
        echo "Starting ILI9488 demo..."
        /usr/bin/ILI9488-demo &
        ;;
    stop)
        killall ILI9488-demo 2>/dev/null
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
